"""Initial Migration

Revision ID: d327ba8ece64
Revises: 
Create Date: 2026-04-07 22:29:20.363749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd327ba8ece64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('platforms', 'api_key',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_platforms_client_id'), 'platforms', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platforms_client_id'), table_name='platforms')
    op.alter_column('platforms', 'api_key',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
